language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
sudo: false
bundler_args: --retry=3 --jobs=3
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
notifications:
  slack:
    secure: ZCYEt/Q5yifjc8ZPyyHr+ugXWpaBYLx6vB1s9g2Mi+VJRGZ08uTCfFizM0yK1Hv3YB5emlPqPGlJHxJxb0ZXzwXGlsRAOE9pTinAaK5oUjVamO7q3ZdGL7FszPRxeRl7HUR5Y+2NcuJjZO7N0wkYUNrDAy0ek3BGAOoKCysC0LA=
